name: 🛡️ Demande de blocage d'IP
description: Signaler une adresse IP malveillante pour ajout à la blocklist.
title: "[BLOCK] : <IP_ADDRESS>"
labels: ["Block Request", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Signalement d'IP Malveillante
        Merci de remplir ce formulaire avec précision pour faciliter l'analyse.

  - type: input
    id: ip_address
    attributes:
      label: Adresse IP cible
      description: L'adresse IPv4 concernée par le signalement.
      placeholder: "ex: 192.168.1.1"
    validations:
      required: true

  - type: dropdown
    id: attack_type
    attributes:
      label: Type d'attaque
      description: Sélectionnez la catégorie principale de l'activité malveillante.
      options:
        - SSH Brute Force
        - Web Scanner / Crawler (e.g. WP Scan)
        - DDoS / DoS / Flood
        - Exploit Attempt (RCE, SQLi, XSS)
        - Mail Spam / Relais
        - Port Scanning
        - Botnet Activity
        - Autre
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Preuves / Logs (Obligatoire)
      description: |
        Copiez ici les extraits de logs (Firewall, Nginx, Auth.log, Fail2Ban) prouvant l'attaque.
        Utilisez des blocs de code pour la lisibilité.
      placeholder: |
        Jan 27 10:00:00 server sshd[12345]: Failed password for invalid user admin from x.x.x.x port 54321 ssh2
      render: shell
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Pourquoi bloquer cette IP ? (Contexte)
      description: Expliquez brièvement le comportement observé ou la fréquence des attaques.
      placeholder: "Cette IP a tenté 500 connexions SSH en moins de 1 minute..."
    validations:
      required: true

  - type: checkboxes
    id: verification
    attributes:
      label: Vérifications
      options:
        - label: Je certifie que ces logs sont authentiques.
          required: true
        - label: J'ai vérifié si possible qu'il ne s'agit pas d'un faux positif ex GoogleBot, IP légitime.
          required: false
